language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kolyakorush/docker-react -f Dockerfile.dev .

#script:
#  - docker run kolyakorush/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "KolyaKorush_docker_react"
  env: "KolyakorushDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-742876190671"
  bucket_path: "KolyaKorush_docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY